---
title: "Week 8: Hierarchical models"
date: today
date-format: "DD/MM/YY"
format: pdf
execute: 
  warning: false
  message: false
---

# Radon

The goal of this lab is to fit this model to the radon data:

$$
\begin{aligned}
y_{i} | \alpha_{j[i]} & \sim N\left(\alpha_{j[i]}+\beta x_{i}, \sigma_{y}^{2}\right), \text { for } i=1,2, \ldots, n \\
\alpha_{j} & \sim N\left(\gamma_{0}+\gamma_{1} u_{j}, \sigma_{\alpha}^{2}\right), \text { for } j=1,2, \ldots, J
\end{aligned}
$$

i.e. varying intercepts, fixed slope on floor. I want you to 

- reproduce the graph on slide 47 
- plot samples from the posterior predictive distribution for a new household in county 2 with basement level measurement, compared to samples from the posterior distribution of the mean county effect in county 2 (i.e., a graph similar to slide 39).

Here's code to get the data into a useful format:

```{r}
library(tidyverse)
# house level data
d <- read.table(url("http://www.stat.columbia.edu/~gelman/arm/examples/radon/srrs2.dat"), header=T, sep=",")

# deal with zeros, select what we want, makke a fips variable to match on 
d <- d |> 
  mutate(activity = ifelse(activity==0, 0.1, activity)) |> 
  mutate(fips = stfips * 1000 + cntyfips) |>   
  dplyr::select(fips, state, county, floor, activity)

# county level data
cty <- read.table(url("http://www.stat.columbia.edu/~gelman/arm/examples/radon/cty.dat"), header = T, sep = ",")
cty <- cty |> mutate(fips = 1000 * stfips + ctfips) |> dplyr::select(fips, Uppm)

# filter to just be minnesota, join them and then select the variables of interest. 
dmn <- d |> 
  filter(state=="MN") |> 
  dplyr::select(fips, county, floor, activity) |> 
  left_join(cty)
head(dmn)

```

Note, in the model:

- $y_i$ is log(activity)
- $x_i$ is floor
- $u_i$ is log(Uppm)


Suggested steps

1. write Stan model (note, you will need samples from post pred distribution, either do in Stan or later in R)
2. Get data in stan format
3. Run the model
4. For $\alpha$ plot, get median estimates of alpha's, and the 2.5th and 97.5th percentiles. Also get the median (mean fine, easier to pull from summary) of the gamma0 and gamma1. You can then use `geom_abline()` to plot mean regression line. 
5. For the predicted y plot, you will need your posterior predictive samples for $y$'s and then just use `geom_density()`
